name: Flake8 Lint
on:
  pull_request:
    branches: [ main ]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: pip install flake8 lintly
      - name: Run Lint with Flake8
        env:
          LINTLY_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: flake8 --ignore=E501 . | lintly --format=flake8 --log --commit-sha=${{ github.event.pull_request.head.sha }} 
